# Generated by Django 5.2.8 on 2025-11-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageasset',
            name='path',
        ),
        migrations.AddField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='cases/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='status',
            field=models.CharField(default='uploaded', max_length=32),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectioncase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InferenceJob',
        ),
    ]
